project:
  type: book

execute: 
  freeze: auto

book:
  title: "GradThesis"
  author: "gaoch@mail.hzau.edu.cn"
  date: now
  chapters:
    - index.qmd
    - intro.qmd
    - part: Student No. 1
      chapters:
        - 01-lzx/data-preprocess.qmd
        - 01-lzx/data-analysis.qmd
    - part: Student No. 2
      chapters:
        - 02-shix/data-preprocess.qmd
        - 02-shix/data-analysis.qmd
    - part: Student No. 3
      chapters:
        - 03-zyt/data-preprocess.qmd
        - 03-zyt/data-analysis.qmd        
    - part: Student No. 4
      chapters:
        - 04-fwfl/data-preprocess.qmd
        - 04-fwfl/data-analysis.qmd    
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{fvextra}
            \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}



