# 数据分析

## 载入需要的包

```{r}
library(tidyverse)
library(ggpubr)
library(kableExtra)

theme_set(theme_bw())
```


## 载入数据

```{r}
file = xfun::magic_path("growth-data.csv")
data = read_csv(file)
```

## 在不同培养基中的生长情况

首先，我们比较一下各个菌株在不同培养基中的生长情况。我们将使用 `ggplot2` 包中的 `geom_boxplot()` 函数来绘制箱线图，并使用 `geom_jitter()` 函数来添加散点图，以便更好地观察数据的分布情况。
我们将使用 `stat_compare_means()` 函数来添加统计显著性标记。该函数可以自动计算 p 值，并在图中添加显著性标记。

这里，我们仅取了 D8 的数据进行比较。

```{r}
#| label: fig-d8-absorbance
#| fig-cap: 各菌株在不同培养基中（共 60 种）的生长情况
#| fig-width: 10
data |> 
  filter(time == "D8") |>
  ggplot(aes(inoculation, absorbance)) +
  geom_boxplot(outliers = FALSE) +
  geom_jitter(aes(color = base_medium), alpha = 0.5, width = 0.2) +
  facet_wrap(~ base_medium, ncol = 1) +
  stat_compare_means(
    ref.group = "blank",
    method = "wilcox.test",
    label = "p.signif",
    hide.ns = TRUE,
    label.y = 1.5,
  ) +
  labs(x = "Inoculation", y = "Absorbance") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


## 生长曲线

这一部分，我们比较各个菌株在不同培养基中的生长曲线。

```{r}
#| label: fig-growth-curve
#| fig-cap: 各菌株在不同培养基中（共 60 种）的生长曲线
#| fig-width: 10
#| fig-height: 8
data |> 
  filter(transformer != "blank", inoculation != "blank") |>
  summarize(
    absorbance = median(absorbance),
    .by = c("inoculation", "time", "base_medium", "transformer")
  ) |> 
  mutate(time = as.numeric(str_extract(time, "\\d+")),
         condition = paste0(base_medium, "-", transformer)) |>
  ggplot(aes(time, absorbance, color = inoculation)) +
  geom_line() +
  facet_wrap(~ condition, ncol = 10)
```


